# Generated by Django 4.2.7 on 2023-11-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "store_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("timestamp_utc", models.DateTimeField()),
                ("status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timezone_str", models.CharField(max_length=50)),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uptime_last_hour", models.IntegerField()),
                ("uptime_last_day", models.IntegerField()),
                ("uptime_last_week", models.IntegerField()),
                ("downtime_last_hour", models.IntegerField()),
                ("downtime_last_day", models.IntegerField()),
                ("downtime_last_week", models.IntegerField()),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.IntegerField()),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.store",
                    ),
                ),
            ],
        ),
    ]
