# Generated by Django 4.2.7 on 2023-11-11 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesshours",
            old_name="day_of_week",
            new_name="day",
        ),
    ]
