# Generated by Django 4.2.7 on 2023-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_rename_day_of_week_businesshours_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=3,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="businesshours",
            name="store_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="storereport",
            name="store_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="timezone",
            name="store_id",
            field=models.CharField(max_length=100),
        ),
    ]
