# Generated by Django 4.2.7 on 2023-11-11 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps",
            "0003_store_id_alter_businesshours_store_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesshours",
            old_name="store_id",
            new_name="store",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="report_id",
            new_name="report",
        ),
        migrations.RenameField(
            model_name="store",
            old_name="store_id",
            new_name="store",
        ),
        migrations.RenameField(
            model_name="storereport",
            old_name="store_id",
            new_name="store",
        ),
        migrations.RenameField(
            model_name="timezone",
            old_name="store_id",
            new_name="store",
        ),
    ]
