# Generated by Django 4.2.7 on 2023-11-11 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps",
            "0005_remove_businesshours_id_remove_timezone_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="businesshours",
            unique_together={("store", "day")},
        ),
    ]
