# Generated by Django 4.2.7 on 2023-11-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_alter_businesshours_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesshours",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=3,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="businesshours",
            name="store",
            field=models.CharField(max_length=100),
        ),
    ]
