# Generated by Django 4.2.7 on 2023-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_businesshours_id_alter_businesshours_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="status",
            field=models.IntegerField(),
        ),
    ]
