# Generated by Django 4.2.7 on 2023-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_alter_store_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="report",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="report",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
