# Generated by Django 4.2.7 on 2023-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps",
            "0009_remove_report_completed_at_remove_report_created_at_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoreReport",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="data",
            new_name="store_data",
        ),
        migrations.RemoveField(
            model_name="report",
            name="report",
        ),
        migrations.RemoveField(
            model_name="report",
            name="status",
        ),
        migrations.RemoveField(
            model_name="store",
            name="status",
        ),
        migrations.AddField(
            model_name="report",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="store",
            name="is_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
