# Generated by Django 4.2.7 on 2023-11-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_timezone_id_alter_businesshours_store_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_importing_data", models.BooleanField(default=False)),
            ],
        ),
    ]
