# Generated by Django 4.2.7 on 2023-11-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0012_importingdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportingData",
        ),
    ]
